language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    - PYTHONPATH="/home/travis/build/json-transformations/jsoncolor"
install: "pip install jsoncut jsonconfig-tool pytest-cov pytest-pep8 coveralls"
script: py.test --cov=jsoncolor --pep8
after_success:
- coveralls
